name: Linux-vcpkg
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: /usr/share/vcpkg/installed
          key: ${{ runner.os }}-vcpkg
      - name: Build Dependencies
        run: |
          vcpkg install openal-soft string-theory
          vcpkg integrate install
          vcpkg list --x-full-desc
