name: macOS CI Hacking
on: [push]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        commit:
          - 63a7a3969609915f41532dd21a749f6d0372e8c3
          - bcff1099c4e83f8eaf8b06b84a54fee325b53b27
    
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: Hoikas/vcpkg
          ref: ${{ matrix.commit }} 
      - run: git log HEAD^..HEAD
      - name: Bootstrap vcpkg
        run: |
          ./bootstrap-vcpkg.sh
      - name: Install Hyperscan
        run: |
          ./vcpkg install hyperscan
