name: macOS CI Hacking
on: [push]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        package:
          - hyperscan
          - ignition-msgs5
          - nettle
          - sdformat9   
    
    steps:
      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: Hoikas/vcpkg
          ref: py3.8
      - name: Bootstrap vcpkg
        run: |
          ./bootstrap-vcpkg.sh
      - name: Install Hyperscan
        run: |
          ./vcpkg install ${{ matrix.package }}
