name: macOS CI Hacking
on: [push]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - hyperscan
          - ignition-msgs5
          - nettle
          - sdformat9   
    
    steps:
      - name: Prepare Environment
        run: |
          brew list autoconf || brew install autoconf
          brew list automake || brew install automake
          brew list libtool || brew install libtool
          brew list pkg-config || brew install pkg-config
      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: Microsoft/vcpkg
          ref: master
      - name: Bootstrap vcpkg
        run: |
          ./bootstrap-vcpkg.sh
      - name: Install ${{ matrix.package }}
        run: |
          ./vcpkg install ${{ matrix.package }}
