name: macOS CI Hacking
on: [push]

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - python3
    
    steps:
      - name: Prepare Environment
        run: |
          brew list autoconf || brew install autoconf
          brew list automake || brew install automake
          brew list libtool || brew install libtool
          brew list pkg-config || brew install pkg-config
      - name: Checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: Hoikas/vcpkg
          ref: py3_interpreter
      - name: Bootstrap vcpkg
        run: |
          ./bootstrap-vcpkg.sh
      - name: Install ${{ matrix.package }}
        run: |
          ./vcpkg install ${{ matrix.package }}
      - name: Upload Build Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package }}-logs
          path: buildtrees/**/*.log
